name: CI

on:
  push:
    branches: [ main, deploy/ocr-analysis-v1 ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY || 'sk-test-dummy-key-for-ci' }}
      NUTRITIONIX_APP_ID: ${{ secrets.NUTRITIONIX_APP_ID || 'test-app-id' }}
      NUTRITIONIX_API_KEY: ${{ secrets.NUTRITIONIX_API_KEY || 'test-api-key' }}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY || 'test-firebase-key' }}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || 'test-domain.firebaseapp.com' }}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID || 'test-project-id' }}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || 'test-bucket' }}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '123456789' }}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID || 'test-app-id' }}
      FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL || 'test@test.com' }}
      FIREBASE_PRIVATE_KEY_BASE64: ${{ secrets.FIREBASE_PRIVATE_KEY_BASE64 || 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRQ29obHlXY2JFOFQvZUgKTUJUNFlzcDlmb1NnbGFGYnJvTWhMbjFNL2VuRmhiR01HNGJLRnRnYnI3QnhDMVRXZStXdDF6clR4ZFYwejY5VQpPVzlXTW1VaG9KU0dRbTJvSGdJU0pzSFhYRkJtbmJZQldKL011WTlpVWJlL1VOZ2JpRWdMa2NmNXkyY0N6V1owCi9UQVZnZVRGQkZ0YnZwWUhCeDRkUzRLS3dqNk5ybXBDYnFRUXUvc0RqS0VEZk83UmlhK1U1WjFiNkp2aDJHSHAKZEJDMnVSaDVzMXlrRlZIM29XcnVQOUxJM3JCWTBCOWljZCtsaG9wcnNqQnU0SzJnbm5lQlRnb0lQVjZhNTVNUwpDM2V0WFc5c0dBanZ1MUJqZzVBRGxORHNaWklsVENJblpEeEg5cE02NlN3R21FQjJJdDJGWUcwaE5tWVZRVU1lClJVdFBZaEp0QWdNQkFBRUNnZ0VBSUEwZWJST0RsUTBzRjVQMkZ5M1JGQzBMdHZsazcvVE9zNlB6MU1CUzU0VHQKSnJrRXBadG1EWTRBWlByMHpTMHNYU3Bjc0oyRnF3TU94UzJtU1lYSW9rd2RmK1VkUHloL0xoUU5QdW9POU5UMQorcmFwcGNIUjZFY0NzYkNDR0oyRm5rSmx3bnJueDNCdEdEck9HT3lBRHY0OGhsaWJUeGR3NWRhTmpuZ3g0aTFkCkwxTWN3aS9YU0RIVnNsSEtzbG9TQ2RzWWFnbXJ5OElmekx1eDBXRDZobW43UGQyQTJEa2pRZ2kwNnRIMUpPZ04KQXIvQ0pLMndoK3hKUUs5N3oxRjJLdHBUditUM3pjb0dPK3Q1RSt0ejhGek9GQnh3amRFcGtlZmhGS3hka3VHcwp0WE1BZ2RHUGVzOEZBbGtYTDJLbW1VTGNMRzBtMTY0eTlnWnF5UUtCZ1FEaFFMSlpLNSt5Z3lRY0p1VkVmQlo1Cm1jb1hLcHcydkJQZkZVbWVZTXhJVGQrUzFnVXpQOFlTSkJ2YTFCemJBUmV0ck50WHZ6SU5pQnVlMnBKbDFVQk8KbFhhZUxUdnBVTjZMbHB3S0VzUGwyL1BWandubmErZWZDRzRTK0swWU80QmdBT3poZi95WGZ5UWtDSXhNaGhUdQpyazVMbHFJdjN4Qko2S0x1dDVHRnl3S0JnUUREQWVVaXU0SUkwaUgrL3kwbE5CWVdMc3IwdDBQTnZrZ0FJcUJuCmEzT0M0Nmt3cGNUS0llOTBSbXdFNmt5OWRUZTdYMmErNlpMSUloeDh6T3A1WjZMRG5pTzJRY3NqcTZLVjhxOWYKUGpYV1ZsdjlZOU5xN1F1dkJ6NlBLNHRYL29ybTRFMzMxRklEbmxnU08ybnFhRDQ2WG9RZC9Pc20ydnZrWGVkVQplN1RMdHdLQmdHUTQxZlJLUzhhVTJicnFiVndrSG10MzJuYWRsWlN3bTV1bVowZjFnUTFrcVZnQVJ5YXI3TlhsCnRIMHF2Qm41QzN2ZUlrb2UwejYzRlBsZ3Y3UUM5azZCYXd1V3NoREtVSXdQdS9mU0l1cWZnQzRHbFVmMnBZbS8KVUd3L2l5Y1hoMTIwbis4RjZDTmdWMFhGeEhGNG5rWHhjODBhZS9EQmxpeEVQWnlZcVROOUFvR0FDRGJHUndwZwpQTkVPS0dhRHJJZEtGajdwdGhiMjkvNytMbFRwaUNnOU5uWlVYQTkyRXdHREFXR0l2S1p2YVkvaTJlSGdkQW1tClJ0LzN4ZURJaytPV1d2eVl2WCtkWHZ2RERkZlZuaVkwOG5NRHRIVzA0Qm1idjBUSkxYTVBIM0xvbmVDU1F3SXEKQzNRK0R0WFZrV24ybkdxcnpSUkMwZ0dLYlREUWppL2RnQnNDZ1lBYm9RcE9LZ01QN1N5cTlBMWNrZWRmaXVQbQo1YWxqK0V0Y1FQT2lrZmluU1NTNFdIbytaWnMrNFI3NUQ2ZFJIeGErR1pZQVkwYzdLZTJBMDg1ZXZ4dG1tK3dzCkg2T0Z2M3RrUFZ0RWNjWWZVQ3hEdUFJOVVQTGwrRWJLaXIyczYzNDZncXU3Qk5NUjRIOHczUktvY21mc2ZhOFAKSVhLQlR5TGZZN1VKdlR3aDdnPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=' }}
      OPENAI_TIMEOUT_MS: "30000"
      USE_OCR_EXTRACTION: "true"
      OCR_CONFIDENCE_THRESHOLD: "0.7"
      OCR_SEGMENTATION_ENABLED: "true"
      USE_GPT4_VISION: "false"

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create .env.local for build
      run: |
        echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> .env.local
        echo "NUTRITIONIX_APP_ID=$NUTRITIONIX_APP_ID" >> .env.local
        echo "NUTRITIONIX_API_KEY=$NUTRITIONIX_API_KEY" >> .env.local
        echo "NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY" >> .env.local
        echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" >> .env.local
        echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID" >> .env.local
        echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET" >> .env.local
        echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" >> .env.local
        echo "NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID" >> .env.local
        echo "FIREBASE_CLIENT_EMAIL=$FIREBASE_CLIENT_EMAIL" >> .env.local
        echo "FIREBASE_PRIVATE_KEY_BASE64=$FIREBASE_PRIVATE_KEY_BASE64" >> .env.local
        echo "OPENAI_TIMEOUT_MS=$OPENAI_TIMEOUT_MS" >> .env.local
        echo "USE_OCR_EXTRACTION=$USE_OCR_EXTRACTION" >> .env.local
        echo "OCR_CONFIDENCE_THRESHOLD=$OCR_CONFIDENCE_THRESHOLD" >> .env.local
        echo "OCR_SEGMENTATION_ENABLED=$OCR_SEGMENTATION_ENABLED" >> .env.local
        echo "USE_GPT4_VISION=$USE_GPT4_VISION" >> .env.local
      
    - name: Build
      run: npm run build
      
    - name: Lint
      run: npm run lint 